# Generated by Django 5.2.18 on 2026-10-10 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_job_level_all_industries'),
        ('employers', '0001_initial'),
        ('jobs', '0002_job_level_all_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày thêm')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_companies', to='candidates.candidateprofile', verbose_name='ứng viên')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employers.company', verbose_name='công ty')),
            ],
            options={
                'verbose_name': 'công ty yêu thích',
                'verbose_name_plural': 'công ty yêu thích',
                'db_table': 'favorite_companies',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'company'), name='uq_favorite_companies_candidate_company')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày thêm')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_jobs', to='candidates.candidateprofile', verbose_name='ứng viên')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jobs.job', verbose_name='tin tuyển dụng')),
            ],
            options={
                'verbose_name': 'việc làm yêu thích',
                'verbose_name_plural': 'việc làm yêu thích',
                'db_table': 'favorite_jobs',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='uq_favorite_jobs_candidate_job')],
            },
        ),
    ]
