# Generated by Django 5.2.18 on 2026-10-07 03:28

import apps.employers.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ngày xóa')),
                ('name', models.CharField(max_length=255, verbose_name='tên công ty')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}(-\\d{3})?$', 'Mã số thuế gồm 10 chữ số (chi nhánh: 10 số + "-" + 3 số).')], verbose_name='mã số thuế')),
                ('logo', models.ImageField(blank=True, max_length=500, upload_to=apps.employers.models.company_logo_path, verbose_name='logo')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9 .()-]{7,19}$', 'Số điện thoại không hợp lệ.')], verbose_name='điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='địa chỉ')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1 - 10 nhân viên'), ('11-50', '11 - 50 nhân viên'), ('51-200', '51 - 200 nhân viên'), ('201-500', '201 - 500 nhân viên'), ('501-1000', '501 - 1000 nhân viên'), ('1000+', 'Trên 1000 nhân viên')], max_length=20, verbose_name='quy mô')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='năm thành lập')),
                ('description', models.TextField(blank=True, verbose_name='giới thiệu')),
                ('verification_status', models.CharField(choices=[('pending', 'Chờ xác minh'), ('verified', 'Đã xác minh'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='trạng thái xác minh')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='xác minh lúc')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.industry', verbose_name='ngành nghề')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.location', verbose_name='tỉnh/thành phố')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='admin xác minh')),
            ],
            options={
                'verbose_name': 'công ty',
                'verbose_name_plural': 'công ty',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='chức danh')),
                ('company_role', models.CharField(choices=[('owner', 'Chủ sở hữu'), ('admin', 'Quản trị'), ('member', 'Thành viên')], default='member', max_length=20, verbose_name='vai trò trong công ty')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('active', 'Đang hoạt động'), ('removed', 'Đã rời công ty')], default='pending', max_length=20, verbose_name='trạng thái')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='tham gia lúc')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruiters', to='employers.company', verbose_name='công ty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to=settings.AUTH_USER_MODEL, verbose_name='tài khoản')),
            ],
            options={
                'verbose_name': 'nhà tuyển dụng',
                'verbose_name_plural': 'nhà tuyển dụng',
                'db_table': 'recruiters',
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['pending', 'verified', 'rejected'])), name='ck_companies_verification_status'),
        ),
        migrations.AddConstraint(
            model_name='recruiter',
            constraint=models.CheckConstraint(condition=models.Q(('company_role__in', ['owner', 'admin', 'member'])), name='ck_recruiters_company_role'),
        ),
        migrations.AddConstraint(
            model_name='recruiter',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'removed'])), name='ck_recruiters_status'),
        ),
    ]
