[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
testpaths = apps
addopts = -q --strict-markers
filterwarnings =
    ignore::DeprecationWarning:rest_framework_simplejwt.*
