# Generated by Django 5.2.18 on 2026-10-07 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='tên')),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('country_code', models.CharField(default='VN', max_length=2, verbose_name='mã quốc gia')),
            ],
            options={
                'verbose_name': 'tỉnh/thành phố',
                'verbose_name_plural': 'tỉnh/thành phố',
                'db_table': 'locations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='tên')),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.industry', verbose_name='ngành cha')),
            ],
            options={
                'verbose_name': 'ngành nghề',
                'verbose_name_plural': 'ngành nghề',
                'db_table': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tên')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Chuyên môn'), ('soft', 'Kỹ năng mềm'), ('language', 'Ngoại ngữ'), ('tool', 'Công cụ'), ('domain', 'Nghiệp vụ')], default='technical', max_length=20, verbose_name='nhóm')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='tên gọi khác')),
                ('is_verified', models.BooleanField(default=False, verbose_name='đã duyệt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
            ],
            options={
                'verbose_name': 'kỹ năng',
                'verbose_name_plural': 'kỹ năng',
                'db_table': 'skills',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['technical', 'soft', 'language', 'tool', 'domain'])), name='ck_skills_category')],
            },
        ),
    ]
