# Generated by Django 5.2.18 on 2026-10-07 03:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='tiêu đề hồ sơ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='giới tính')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='địa chỉ')),
                ('summary', models.TextField(blank=True, verbose_name='giới thiệu')),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='số năm kinh nghiệm')),
                ('current_level', models.CharField(blank=True, choices=[('intern', 'Thực tập sinh'), ('fresher', 'Fresher'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Trưởng nhóm'), ('manager', 'Quản lý')], max_length=20, verbose_name='cấp bậc hiện tại')),
                ('desired_position', models.CharField(blank=True, max_length=150, verbose_name='vị trí mong muốn')),
                ('desired_salary_min', models.BigIntegerField(blank=True, null=True, verbose_name='lương mong muốn từ')),
                ('desired_salary_max', models.BigIntegerField(blank=True, null=True, verbose_name='lương mong muốn đến')),
                ('salary_currency', models.CharField(default='VND', max_length=3, verbose_name='tiền tệ')),
                ('desired_job_type', models.CharField(blank=True, choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('internship', 'Thực tập'), ('contract', 'Hợp đồng'), ('freelance', 'Freelance')], max_length=20, verbose_name='hình thức mong muốn')),
                ('desired_work_mode', models.CharField(blank=True, choices=[('onsite', 'Tại văn phòng'), ('remote', 'Từ xa'), ('hybrid', 'Linh hoạt (hybrid)')], max_length=20, verbose_name='chế độ làm việc mong muốn')),
                ('is_open_to_work', models.BooleanField(default=True, verbose_name='đang tìm việc')),
                ('is_public', models.BooleanField(default=False, verbose_name='cho phép NTD tìm thấy')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.location', verbose_name='tỉnh/thành phố')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='tài khoản')),
            ],
            options={
                'verbose_name': 'hồ sơ ứng viên',
                'verbose_name_plural': 'hồ sơ ứng viên',
                'db_table': 'candidate_profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('years_of_experience__gte', 0)), name='ck_candidate_years_non_negative'), models.CheckConstraint(condition=models.Q(('desired_salary_max__isnull', True), ('desired_salary_min__isnull', True), ('desired_salary_max__gte', models.F('desired_salary_min')), _connector='OR'), name='ck_candidate_desired_salary_range')],
            },
        ),
    ]
