# Generated by Django 5.2.18 on 2026-10-07 03:28

import apps.accounts.managers
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='họ tên')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9 .()-]{7,19}$', 'Số điện thoại không hợp lệ.')], verbose_name='số điện thoại')),
                ('role', models.CharField(choices=[('candidate', 'Ứng viên'), ('employer', 'Nhà tuyển dụng'), ('admin', 'Quản trị viên')], max_length=20, verbose_name='vai trò')),
                ('is_active', models.BooleanField(default=True, verbose_name='đang hoạt động')),
                ('is_staff', models.BooleanField(default=False, verbose_name='quyền vào trang quản trị')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='xác thực email lúc')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ngày xóa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'người dùng',
                'verbose_name_plural': 'người dùng',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['candidate', 'employer', 'admin'])), name='ck_users_role')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
