# Generated by Django 5.2.18 on 2026-10-07 03:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ngày xóa')),
                ('title', models.CharField(max_length=255, verbose_name='tiêu đề')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(verbose_name='mô tả công việc')),
                ('requirements', models.TextField(verbose_name='yêu cầu ứng viên')),
                ('benefits', models.TextField(blank=True, verbose_name='quyền lợi')),
                ('job_type', models.CharField(choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('internship', 'Thực tập'), ('contract', 'Hợp đồng'), ('freelance', 'Freelance')], max_length=20, verbose_name='hình thức')),
                ('work_mode', models.CharField(choices=[('onsite', 'Tại văn phòng'), ('remote', 'Từ xa'), ('hybrid', 'Linh hoạt (hybrid)')], default='onsite', max_length=20, verbose_name='chế độ làm việc')),
                ('level', models.CharField(choices=[('intern', 'Thực tập sinh'), ('fresher', 'Fresher'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Trưởng nhóm'), ('manager', 'Quản lý')], max_length=20, verbose_name='cấp bậc')),
                ('min_years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='số năm kinh nghiệm tối thiểu')),
                ('salary_min', models.BigIntegerField(blank=True, null=True, verbose_name='lương từ')),
                ('salary_max', models.BigIntegerField(blank=True, null=True, verbose_name='lương đến')),
                ('salary_currency', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD')], default='VND', max_length=3, verbose_name='tiền tệ')),
                ('is_salary_negotiable', models.BooleanField(default=False, verbose_name='lương thỏa thuận')),
                ('headcount', models.PositiveSmallIntegerField(default=1, verbose_name='số lượng tuyển')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='địa chỉ làm việc')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='hạn nộp hồ sơ')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đang tuyển'), ('paused', 'Tạm dừng'), ('closed', 'Đã đóng'), ('expired', 'Hết hạn')], default='draft', max_length=20, verbose_name='trạng thái')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='đăng lúc')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='đóng lúc')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='lượt xem')),
                ('application_count', models.PositiveIntegerField(default=0, verbose_name='số hồ sơ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='employers.company', verbose_name='công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người tạo')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.industry', verbose_name='ngành nghề')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.location', verbose_name='tỉnh/thành phố')),
            ],
            options={
                'verbose_name': 'tin tuyển dụng',
                'verbose_name_plural': 'tin tuyển dụng',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='bắt buộc')),
                ('min_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='số năm tối thiểu')),
                ('weight', models.PositiveSmallIntegerField(default=3, verbose_name='trọng số')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='catalog.skill')),
            ],
            options={
                'verbose_name': 'kỹ năng yêu cầu',
                'verbose_name_plural': 'kỹ năng yêu cầu',
                'db_table': 'job_skills',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkill', to='catalog.skill', verbose_name='kỹ năng'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='uq_job_skills_job_skill'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 1), ('weight__lte', 5)), name='ck_job_skills_weight_range'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', '-created_at'], name='idx_jobs_company'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'published')), fields=['-published_at'], name='idx_jobs_public_list'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'published')), fields=['location', 'level', 'job_type'], name='idx_jobs_filter'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'paused', 'closed', 'expired'])), name='ck_jobs_status'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('job_type__in', ['full_time', 'part_time', 'internship', 'contract', 'freelance'])), name='ck_jobs_job_type'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('work_mode__in', ['onsite', 'remote', 'hybrid'])), name='ck_jobs_work_mode'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['intern', 'fresher', 'junior', 'middle', 'senior', 'lead', 'manager'])), name='ck_jobs_level'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__gte', 0)), name='ck_jobs_salary_min_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_max__isnull', True), ('salary_min__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='ck_jobs_salary_range'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('headcount__gt', 0)), name='ck_jobs_headcount_positive'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('min_years_experience__gte', 0)), name='ck_jobs_min_years_non_negative'),
        ),
    ]
