# Generated by Django 5.2.18 on 2026-10-07 03:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('cvs', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('cover_letter', models.TextField(blank=True, verbose_name='thư giới thiệu')),
                ('status', models.CharField(choices=[('applied', 'Mới ứng tuyển'), ('screening', 'Đang sàng lọc'), ('interview', 'Phỏng vấn'), ('offer', 'Đề nghị nhận việc'), ('hired', 'Đã tuyển'), ('rejected', 'Từ chối'), ('withdrawn', 'Ứng viên đã rút')], default='applied', max_length=20, verbose_name='trạng thái')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='lý do từ chối')),
                ('recruiter_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='đánh giá của NTD (1-5)')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='đổi trạng thái lúc')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile', verbose_name='ứng viên')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cvs.cv', verbose_name='CV đã nộp')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.job', verbose_name='tin tuyển dụng')),
            ],
            options={
                'verbose_name': 'hồ sơ ứng tuyển',
                'verbose_name_plural': 'hồ sơ ứng tuyển',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='từ trạng thái')),
                ('to_status', models.CharField(max_length=20, verbose_name='sang trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='thời điểm')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người thay đổi')),
            ],
            options={
                'verbose_name': 'lịch sử trạng thái',
                'verbose_name_plural': 'lịch sử trạng thái',
                'db_table': 'application_status_history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='idx_applications_job_status'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', '-created_at'], name='idx_applications_candidate'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'candidate'), name='uq_applications_job_candidate'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['applied', 'screening', 'interview', 'offer', 'hired', 'rejected', 'withdrawn'])), name='ck_applications_status'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('recruiter_rating__isnull', True), models.Q(('recruiter_rating__gte', 1), ('recruiter_rating__lte', 5)), _connector='OR'), name='ck_applications_rating_range'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', 'created_at'], name='idx_app_history_app'),
        ),
    ]
