# Generated by Django 5.2.18 on 2026-10-07 03:28

import apps.cvs.models
import common.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ngày xóa')),
                ('title', models.CharField(max_length=150, verbose_name='tên CV')),
                ('file', models.FileField(max_length=500, storage=common.storage.private_storage, upload_to=apps.cvs.models.cv_file_path, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='tên file gốc')),
                ('mime_type', models.CharField(choices=[('application/pdf', 'PDF'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX')], max_length=100, verbose_name='định dạng')),
                ('file_size', models.PositiveIntegerField(verbose_name='dung lượng (byte)')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='ngôn ngữ')),
                ('is_default', models.BooleanField(default=False, verbose_name='CV mặc định')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='candidates.candidateprofile', verbose_name='ứng viên')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
                'db_table': 'cvs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', '-created_at'], name='idx_cvs_candidate')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mime_type__in', ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'])), name='ck_cvs_mime_type'), models.CheckConstraint(condition=models.Q(('file_size__gt', 0)), name='ck_cvs_file_size_positive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('candidate',), name='uq_cvs_default')],
            },
        ),
    ]
