# Generated by Django 5.2 on 2026-10-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='trạng thái bóc tách'),
        ),
        migrations.AddField(
            model_name='cv',
            name='parse_error',
            field=models.TextField(blank=True, verbose_name='lỗi bóc tách'),
        ),
        migrations.AddField(
            model_name='cv',
            name='raw_text',
            field=models.TextField(blank=True, verbose_name='văn bản trích xuất'),
        ),
        migrations.AddField(
            model_name='cv',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='dữ liệu bóc tách'),
        ),
        migrations.AddField(
            model_name='cv',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bóc tách lúc'),
        ),
        migrations.AddConstraint(
            model_name='cv',
            constraint=models.CheckConstraint(condition=models.Q(('parse_status__in', ['pending', 'processing', 'completed', 'failed'])), name='ck_cvs_parse_status'),
        ),
    ]
